apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eomp9n7e1-python
  janus-idp.io/tekton: eomp9n7e1-python
  backstage.io/kubernetes-id: eomp9n7e1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eomp9n7e1-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
